BUG: Fix windows compilation error C2664
Commenting the #ifdef WIN32 seems to fix the problem.


The text below illustrates the error:

Line 677
'QString::fromUtf16' : cannot convert parameter 1 from 'Py_UNICODE *' to 'const ushort *'
Types pointed to are unrelated; conversion requires reinterpret_cast, C-style cast or function-style cast

Line 1044
'PyUnicodeUCS2_FromUnicode' : cannot convert parameter 1 from 'const ushort *' to 'const Py_UNICODE *'
Types pointed to are unrelated; conversion requires reinterpret_cast, C-style cast or function-style cast